### ISSUE TITLE
Можно ли сделать такое же для английского языка?

### ISSUE THREAD

**Issue by anpleenko** [rtivital/proschet#1]
В проектах иногда требуется для английского языка сделать множественную форму

**Comment by rtivital** [comment]
В английском языке всё проще гораздо. Единственное и множественное число: 1 thing, 2 things, 3 things...

**Comment by anpleenko** [comment]
Конечно проще чем у нас, но хочется чтобы было на уровне библиотеки и своих костылей не надо городить, типо

```
value > 1 ? 'things' : 'thing'
```
