### ISSUE TITLE
This lib on web javascript

### ISSUE THREAD

**Issue by metroyanno** [rtivital/proschet#2]
Can I do it? And why?

**Comment by rtivital** [comment]
Sorry, I don't actually understand what do you want

**Comment by metroyanno** [comment]
First. Are you Russian?
Second. I need import this library to web browser javascript

**Comment by rtivital** [comment]
Yes, i am. I will enable this in the future releases, until then maybe the best solution for you will be just copying source code in your project?

```js


const CASES = [2, 0, 1, 1, 1, 2];


function proschet(titles) {
  return function bindedProschet(amount) {
    return titles[
      (amount % 100 > 4 && amount % 100 < 20) ? 2 : CASES[(amount % 10 < 5) ? amount % 10 : 5]
    ];
  };
}
```

**Comment by metroyanno** [comment]
Думаю, что затруднений больше не будет, придется только код на PHP еще переписать
